### ISSUE TITLE
Add deprecation notice?

### ISSUE THREAD

**Issue by Eoksni** [gcanti/logging-ts#6]
Seems like it doesn't support `fp-ts@2` and I suggest to inform about it in the readme.

Not to complain, but I'm new to `fp-ts` and hardcore FP in general and I've spent quite a bit of time trying to understand what I'm doing wrong with `logging-ts` only to finally realise that it uses `fp-ts` version 1 instead of version 2.

**Comment by gcanti** [comment]
(btw this package is not deprecated, I just had no time to upgrade yet)

**Comment by Eoksni** [comment]
Yeah, I guess deprecation wasn't the right word, more like 'outdated'. Btw looking forward to become more familiar with fp-ts, it looks awesome :) Thanks for the amazing work.
