### ISSUE TITLE
Migration to fp-ts 2.0

### ISSUE THREAD

**Issue by mstn** [gcanti/logging-ts#8]
Hello, 

I saw the "coming soon" note in the `README` for a version of this package working with `fp-ts@2.0`. 

I was just wondering if I can take it over or you are already working on it. In the first case, do you have any recommendation? Probably, we can remove the class `Logger`.

Thanks!

**Comment by gcanti** [comment]
https://github.com/gcanti/logging-ts/releases/tag/0.3.0
